
fastlane_version '2.54.4'

default_platform :ios

require 'plist'
require 'xcodeproj'

require_relative 'pushify'

platform :ios do
  desc 'Runs all the tests'
  lane :test do
    scan
  end

  desc 'Sets the Push Entitlement'
  lane :enable_push do |options|
    Pushify.enable_push(options[:push_type])
    UI.message('Enabled push')
  end

  desc 'Removes the Push Entitlement'
  lane :disable_push do
    Pushify.enable_push('none')
    UI.message('Disabled push')
  end

  desc 'Builds the application with the given options'
  lane :build do |options|
    if %w[development production].include? options[:push_type]
      # detour to the :enable_push lane so that we can
      #   make sure that push is enabled
      enable_push options
    else
      # detour to the :enable_push lane so that we can
      #   make sure that push is disabled
      disable_push
    end
    gym(workspace: Notif10Swift.worskspace_filepath)
  end
end
